// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQ38ysRHJEp_EWb5F2YMUP6Ty7hyoAgE',
    appId: '1:837573507624:web:4af54d4433b8372307531d',
    messagingSenderId: '837573507624',
    projectId: 'fluttertest-e9ea1',
    authDomain: 'fluttertest-e9ea1.firebaseapp.com',
    storageBucket: 'fluttertest-e9ea1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8Ho7N74qqzSspnZIzTYZQAvXs2PiNuE',
    appId: '1:837573507624:android:865b52f0d45a269807531d',
    messagingSenderId: '837573507624',
    projectId: 'fluttertest-e9ea1',
    storageBucket: 'fluttertest-e9ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlRbkPqwtpp4R7MdjhYdpiKnIOb6dtBc',
    appId: '1:837573507624:ios:a7467483d5931af107531d',
    messagingSenderId: '837573507624',
    projectId: 'fluttertest-e9ea1',
    storageBucket: 'fluttertest-e9ea1.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlRbkPqwtpp4R7MdjhYdpiKnIOb6dtBc',
    appId: '1:837573507624:ios:a7467483d5931af107531d',
    messagingSenderId: '837573507624',
    projectId: 'fluttertest-e9ea1',
    storageBucket: 'fluttertest-e9ea1.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQ38ysRHJEp_EWb5F2YMUP6Ty7hyoAgE',
    appId: '1:837573507624:web:e07e1dbe0969b42f07531d',
    messagingSenderId: '837573507624',
    projectId: 'fluttertest-e9ea1',
    authDomain: 'fluttertest-e9ea1.firebaseapp.com',
    storageBucket: 'fluttertest-e9ea1.firebasestorage.app',
  );
}
